---
es_version: "7.12.1"
es_use_snapshot_release: false
oss_version: false
es_package_name: "elasticsearch"
es_version_lock: false
es_use_repository: true
es_add_repository: true
es_templates_fileglob: ""
es_start_service: true
es_java_install: "{{ false if (es_version is version('7.0.0', '>=')) else true }}"
update_java: false
es_restart_on_change: true
es_plugins_reinstall: false
es_templates: false
es_user: elasticsearch
es_group: elasticsearch
es_config: {}
es_config_default: "elasticsearch.j2"
es_config_log4j2: ""
es_config_jvm: "jvm.options.j2"
es_conf_dir: "/etc/elasticsearch"
es_pid_dir: "/var/run/elasticsearch"
es_tmp_dir: "/tmp"
es_data_dirs:
  - "/var/lib/elasticsearch"
es_log_dir: "/var/log/elasticsearch"
es_action_auto_create_index: true
es_max_open_files: 65536
es_max_map_count: 262144
es_allow_downgrades: false
es_xpack_trial: false
es_api_scheme: "http"
es_api_host: "localhost"
es_api_port: 9200
es_api_uri: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}"
es_api_sleep: 15
# JVM custom parameters
es_java_home: ''
es_jvm_custom_parameters: ''
es_heap_dump_path: "/var/lib/elasticsearch"